[package]
name = "gpustat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.20.1"
egui_extras = "0.20.0"
nvml-wrapper = "0.8.0"
nvml-wrapper-sys = "0.6.0"
sysinfo = "0.27.1"
